# Generated by Django 6.0.5 on 2026-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_transaction_moneyid_alter_transaction_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='moneyid',
            field=models.CharField(max_length=100),
        ),
    ]
