# Generated by Django 6.0.5 on 2026-05-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_alter_transaction_moneyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='endprice',
            field=models.FloatField(max_length=100, null=True),
        ),
    ]
