# Generated by Django 6.0.5 on 2026-05-21 05:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_transaction_endprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='count',
            field=models.FloatField(max_length=100, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
