# Generated by Django 6.0.5 on 2026-05-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_userb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userb',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
