# Generated by Django 6.0.5 on 2026-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_profile_delete_userb'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], default=60, max_length=4),
            preserve_default=False,
        ),
    ]
