# Generated by Django 6.0.5 on 2026-05-22 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_alter_transaction_count_alter_transaction_endprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='count',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
