# Generated by Django 6.0.5 on 2026-05-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_alter_transaction_count_alter_transaction_endprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='endprice',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=20, max_digits=30),
        ),
    ]
